### ISSUE TITLE
This library seems to violate Postel's Law

### ISSUE THREAD

**Issue by iakobos** [testdouble/diplomat#6]
First, I want to say that this seems like a great attempt to fill a need, API testing has not received nearly enough attention and the language agnosticism and feature set are compelling. That being said, [Postel's Law](https://en.wikipedia.org/wiki/Robustness_principle) says "be conservative in what you do, be liberal in what you accept from others". I think the principle that `diplomat` adopts around strictness ("Strict by default: When something is not specified, the defaults should be as restrictive as possible, e.g. keys not specified in JSON entities are forbidden, rather than ignored.") violates Postel's law because it asserts that every test should care about every output rather then allowing an API to evolve over time to meet the demands of its consumers, which, if I'm understanding correctly, would require every API evolution to require a change in all the `diplomat` tests for that API.

Since I mostly work on internal APIs, I think [Consumer driven contract tests](https://www.martinfowler.com/articles/consumerDrivenContracts.html) are vastly superior to end-to-end API tests and [Pact](https://docs.pact.io/index.html) is my tool of choice, but if `diplomat` is meant to be useful for public APIs, then consumer-driven contract tests are not a good fit (and Pact doesn't have the feature set that `diplomat` does), but I still would be interested in your thoughts about the strictness requirement, in my experience the cost outweighs the benefits.

**Comment by Schoonology** [comment]
Why hello, good Sir!

Keep in mind that those goals are potentially (read: probably) out of date. This project went from "here are my thoughts, I'll get to implementing them eventually" to "all of my time is spent on this" to "time to dogfood" in the scope of a month or so; the documentation has suffered the most as a result.

On to Postel's Law.

While I am in favor of following this Law, it's not _necessarily_ a reasonable goal for every piece of software. Diplomat, specifically, is responsible for _enforcing_ Postel's Law more than it is responsible for _following_ it. Put another way, it is the goal of Diplomat to hold the HTTP APIs under test to the latter half of the Law: they should be _extremely_ conservative in what they respond with.

We handle this in two ways. If you provide a _literal_ response entity, we expect that entire entity is valid with respect to the `Content-Type` you have provided (falling back—speaking of Postel's—to the `Content-Type` found in the actual response); in the case of a JSON response, we check key-by-key, but in the case of, say, an `image/png` response, we'll do a byte-by-byte comparison. Both of these are intended to be as strict as possible, because you've told us the response should _literally_ be as specified.

On the other hand if you provide a _validator function_ in response definition (like, say, `json_schema(...)`), you're only expected to satisfy that function, which can be as loose as it likes. In the case of JSON Schema, provided _currently_ as `json_schema`, you could use `{ "type": "object" }` or `{ "type": "array" }` and be done with it.

Does this address the issue? Do you want to discuss this further?

**Comment by iakobos** [comment]
@Schoonology Thanks for the response! Hope I wasn't too terse as to suggest that isn't a cool library, I'm looking at using it to replace some API tests that I'm just currently using `curl` + `bats` + fixtures to test (🤢) and it looks like a great fit. Thinking about it more, I think you're right that `json_schema` provides the flexibility to evolve APIs without causing rippling test failures. I looked through the examples, but didn't really connect the dots that using `json_schema` would address my concerns, and it definitely does. As to your remark about Postel's Law not being necessarily desirable for all cases is a good point, and one I didn't consider because I'm a zealot 😬.
